---
title: |
  | Solving and Estimating
  | an Incomplete Information Entry Game
shorttitle: Empirical Industrial Organization
shortauthors: Lezama
author:
- name: Carlos Enrique Lezama Jacinto
  affiliation: |
    |
    | Instituto Tecnológico
    | Autónomo de México
  address: |
    |
    | clezamaj\@itam.mx
classoption: [cm, linguex]
bibliography: ref.bib
output: 
  rticles::glossa_article:
    citation_package: natbib
    includes:
      in_header: "preamble.tex"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Setup

Suppose there are two firms, $A$ and $B$, that simultaneously decide whether to enter in the market $m \in \{1, \dots, M\}$ or not. If firm $i \in \{A, B\}$ decides to enter, its profits are given by

$$
\Pi_{i, m} = X_{i, m} \beta - D_{j, m} \alpha + \nu_m + u_{i, m}, \quad \forall\ i, j \in \{A, B\},\ i \neq j
$$

where $X_{i, m}$ is an observable characteristic of firm $i$ that boosts profits in market $m$, $D_{j, m} \in \{0, 1\}$ is $j$'s decision of entering the market, $\nu_m$ is a market fixed effect, and $u_{i, m}$ captures unobserved idiosyncratic shocks to profits.

On the other hand, if firm $i$ decides not to enter market $m$, its profits are zero.

Notice that $u_{i, m}$ is observed by $i$ but not by its opponent $j$. Consequently, the firms are playing an incomplete information entry game described below.

\begin{center}
\begin{tabular}{cc|c|c|}
	& \multicolumn{1}{c}{} & \multicolumn{2}{c}{Firm $B$}\\
	                        & \multicolumn{1}{c}{} & \multicolumn{1}{c}{Enter}                             & \multicolumn{1}{c}{Do not enter}                      \\\cline{3-4}
	\multirow{2}*{Firm $A$} & Enter                & $\left(\Pi_{A ,m}, \Pi_{B, m}\right)$                 & $\left( X_{A, m} \beta + \nu_m + u_{A, m}, 0 \right)$ \\\cline{3-4}
	                        & Do not enter         & $\left( 0, X_{B, m} \beta + \nu_m + u_{B, m} \right)$ & $\left(0, 0\right)$                                   \\\cline{3-4}
\end{tabular}
\end{center}

Thus, the expected profits of firm $A$ if it decides to enter market $m$ are

\begin{align*}
	\ev\left(\Pi_{A, m}\right) & = \left( D_{A, m} \right) \left( p(D_{B, m} = 1) \left( X_{A, m} \beta - \alpha + \nu_m + u_{A, m} \right) \right. \\ &+ \left. \left( 1 - p(D_{B, m} = 1)\right) \left( X_{A, m} \beta - \alpha + u_{A, m} \right) \right) \\
	&+ \left( 1 - D_{A, m} \right) \cdot 0
\end{align*}

where, $\forall\ i, j \in \{A, B\}$, $i \neq j$, the condition for firm $i$ to enter the market in terms of its expected profits is defined as follows:

\begin{align*}
	D_{i, m} & = \mathbf{1} \left( p(D_{j, m} = 1) \left( X_{i, m} \beta - \alpha + \nu_m + u_{i, m} \right) \right. \\ &+ \left. \left( 1 - p(D_{j, m} = 1) \right) \left( X_{i, m} \beta + \nu_m + u_{i, m} \right) > 0 \right) .
\end{align*}

Namely, the probability that firm $A$ enters market $m$ is

\begin{align*}
	p \left(D_{A, m} = 1\right) & = p \left( X_{A, m} \beta - \alpha p \left( D_{B, m} = 1 \right) + \nu_m + u_{A, m} > 0 \right)              \\
	                                & = p \left( u_{A, m} > - \left( X_{A, m} \beta - \alpha p \left( D_{B, m} = 1 \right) + \nu_m \right) \right) \\
	                                & = \Phi \left( X_{A, m} \beta - \alpha p \left( D_{B, m} = 1 \right) + \nu_m \right)                              
\end{align*}

where $\Phi = \dnorm (0, 1)$. Recall that we assume $u_{i, m} \sim \dnorm(0, 1)$, $\forall\ i, j \in \{A, B\}$, $i \neq j$.

Similarly,

$$
p \left( D_{B, m} = 1 \right) = \Phi \left( X_{B, m} \beta - \alpha p \left( D_{A, m} = 1 \right) + \nu_m \right) .
$$

Henceforth, let $p_{i, m} = p(D_{i, m} = 1)$.

\newpage

# Simulations

We propose the following parametrization to simulate our model:

\begin{align*}
&\alpha =  2 && X_{A,m} \sim \dunif(0, 1) \\
&\beta = 0.2 && X_{B, m} \sim \dunif(0.1, 1.4) \\
&\nu_m = 0.9 \times \mathbf{1} \{ m \leq 100 \} && u_{A, m}, u_{B, m} \overset{\iid}{\sim} \dnorm(0, 1)
\end{align*}

With this setup, we obtain the following entry probabilities for markets 1, 101, 201, 301, and 401.

| $m$ | $p_{A, m}$ | $p_{B, m}$ |
| :-: | :--------: | :--------: |
|  1  |   0.6019   |   0.4001   |
| 101 |   0.3172   |   0.2766   |
| 201 |   0.3375   |   0.2805   |
| 301 |   0.3812   |   0.2503   |
| 401 |   0.2590   |   0.3362   |

Thus, firm $A$ enters 165 markets while firm $B$ enters 179. However, recall that Bayesian Nash equilibrium allows for ex-post regret where profits are negative succeeding the decision of entry. In our case, firm $A$ regrets 41 times while $B$ regrets 48---24.85% and 26.82%, respectively.

\newpage

# Maximum Likelihood

In pursuit of our estimation objectives for $\theta = (\alpha, \beta, \gamma)$ such that $\gamma$ appears in $\nu_m := \gamma \times \mathbf{1} \{ m \leq 100 \}$---i.e., we also want to estimate a common market fixed effect for the first 100 markets---we define our log-likelihood function as shown below.

\begin{align*}
\log\mathcal{L}_{m} (\theta \mid \cdot) &= \sum_{m = 1}^{M} \left[ D_{A, m} D_{B, m} \log(p_{A, m} p_{B, m}) \right. \\
&+ D_{A, m} (1 - D_{B, m}) \log(p_{A, m} (1 - p_{B, m})) \\
&+ (1 - D_{A, m}) D_{B, m} \log((1 - p_{A, m}) p_{B, m}) \\
&+ \left. (1 - D_{A, m}) (1 - D_{B, m}) \log((1 - p_{A, m}) (1 - p_{B, m})) \right]
\end{align*}

The maximum likelihood estimates, as well as their standard errors, are shown in the following table.

| Parameter | Estimate |   SE   |
| :-------: | :------: | :----: |
| $\alpha$  |  2.0347  | 0.1813 |
|  $\beta$  |  0.1915  | 0.0470 |
| $\gamma$  |  0.7421  | 0.1865 |

\newpage

# GMM

With the generalized method of moments (GMM), we may want to consider up to the fourth moment to ensure over-identification. This way, we can describe an algorithm that performs GMM estimation as follows:

1. Compute $\theta^{(0)} = \arg\min_\theta \bar{g}(\theta)'\bar{g}(\theta)$
2. Compute the heteroskedasticity and auto-correlation consistent matrix $\hat{\Omega} \left(\theta^{(0)}\right)$ like the one proposed by @HAC
3. Compute $\theta^{(0)} = \arg\min_\theta \bar{g}(\theta)'\left[\hat{\Omega} \left(\theta^{(0)}\right)\right]^{-1}\bar{g}(\theta)$
4. If $\left\lVert \theta^{(0)} - \theta^{(1)} \right\rVert < \varepsilon$, stop; else, $\theta^{(0)} = \theta^{(1)}$ and repeat from 2
5. Define $\hat{\theta} = \theta^{(1)}$

\newpage
